ARCHS = armv7 arm64

include theos/makefiles/common.mk

BUNDLE_NAME = JUSTDOIT
JUSTDOIT_FILES = Switch.x
JUSTDOIT_FRAMEWORKS = UIKit
JUSTDOIT_LIBRARIES = flipswitch
JUSTDOIT_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk